---
name: Bertrand
surname: Tornil
position: "Principal Software Engineer"
address: "Wake Forest, NC 27587"
www: www.tornil.net
email: "bertrand.tornil@gmail.com"
twitter: bobuss
github: bobuss
linkedin: bertrandtornil
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

* PhD in Computer Sciences
* Web Application Architectures
* Data Platform Architectures
* DevOps
* Open Source Technologies

# Technical skills

```{r}
library(tibble)
tribble(
  ~ Cat, ~ Desc,
  "In short", "I deliver available, scalable and observable web services.",
  "Languages", "Python, Javascript, Go",
  "Databases / NoSQL / Timeseries", "MariaDB, PostgreSQL, MySQL, Redis, Memcache, Clickhouse, Prometheus, Orchestrator",
  "Other Data related stuff", "Kafka, Google BigQuery",
  "Cloud", "Azure (+++), AWS (++), GCP (+)",
  "Containers", "Kubernetes, AKS, Docker, Compose, ECS",
  "Devops", "Ansible, Terraform, Continuous Integration, Prometheus, Grafana, Consul, SigNoz, Jaeger, OpenTelemetry",
  "OS", "RedHat, Ubuntu",
  "Misc.", "frontend hobbyist, currently playing with vue.js and audioworkers API, used to be on-call"
) %>% 
  brief_entries(Desc, Cat)
```


# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Doctor of Philosophy in Information Systems", "2006", "Université Paul Sabatier", "Toulouse, France",
  "Master of Science in Computer Information", "2001", "Université Paul Sabatier", "Toulouse, France",
  "Bachelor of Science in Computer Science", "1999", "Université of Limoges", "Limoges, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Professionnal experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Conferences and Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("biblio.bib") %>%
  arrange(desc(issued), issued)
```
